#!/bin/bash
set -Eeuo pipefail

: "${FAKE_CURL_SOURCE:?}"
destination=''
while (( $# > 0 )); do
  case "$1" in
    --output)
      (( $# >= 2 )) || exit 64
      destination="$2"
      shift 2
      ;;
    *) shift ;;
  esac
done
[[ -n "$destination" ]] || exit 64
cp -- "$FAKE_CURL_SOURCE" "$destination"
